[package]
name = "omacell-gui"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
publish.workspace = true
description = "Graphical front-end for Omacell."

[lints]
workspace = true

[dependencies]
eframe = { version = "0.32", default-features = false, features = ["wgpu", "accesskit", "default_fonts", "wayland", "x11"] }
egui = "0.32"
omacell-bus = { path = "../bus", version = "0.0.0" }
omacell-conf = { path = "../conf", version = "0.0.0" }
omacell-core = { path = "../core", version = "0.0.0" }
omacell-ui = { path = "../ui", version = "0.0.0" }
serde_json = { workspace = true }

[dev-dependencies]
egui_kittest = { version = "0.32", features = ["wgpu", "snapshot", "eframe"] }
omacell-fn = { path = "../fn", version = "0.0.0" }
criterion = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
tempfile = "3"

[[bench]]
name = "scroll"
harness = false
