[package]
name = "omacell-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.omacell-core]
path = "../crates/core"

[[bin]]
name = "parse_formula"
path = "fuzz_targets/parse_formula.rs"
test = false
doc = false
bench = false

[[bin]]
name = "parse_numfmt"
path = "fuzz_targets/parse_numfmt.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
