//! Deterministic command reference generation from the Clap command tree.

use std::fmt::Write as _;

use clap::Command;

/// Render the complete command tree as Markdown for the shipped manual.
///
/// The output is generated from the same [`Command`] used by argument parsing,
/// completions, and the man page, so CI can reject stale command documentation.
#[must_use]
pub fn command_reference_markdown() -> String {
    let mut output = String::from(
        "<!-- Generated by `cargo run -p omacell-cli --example generate-docs`; do not edit. -->\n\n# CLI reference\n\n",
    );
    render_command(crate::command(), "omacell", 2, &mut output);
    while output.ends_with('\n') {
        output.pop();
    }
    output.push('\n');
    output
}

fn render_command(mut command: Command, invocation: &str, level: usize, output: &mut String) {
    let heading = "#".repeat(level);
    let _ = writeln!(output, "{heading} `{invocation}`\n");
    let _ = writeln!(output, "```text");
    let help = command.render_long_help().to_string();
    for line in help.trim_end().lines() {
        let _ = writeln!(output, "{}", line.trim_end());
    }
    let _ = writeln!(output, "```\n");

    let children = command
        .get_subcommands()
        .map(|child| child.get_name().to_owned())
        .collect::<Vec<_>>();
    for name in children {
        let Some(child) = command.find_subcommand(&name).cloned() else {
            continue;
        };
        let child_invocation = format!("{invocation} {name}");
        render_command(child, &child_invocation, level + 1, output);
    }
}

#[cfg(test)]
mod tests {
    use super::command_reference_markdown;

    #[test]
    fn reference_includes_nested_commands() {
        let reference = command_reference_markdown();
        assert!(reference.contains("## `omacell`"));
        assert!(reference.contains("### `omacell convert`"));
        assert!(reference.contains("#### `omacell ai setup`"));
        assert!(reference.contains("--from-workbook"));
        assert!(reference.lines().all(|line| line == line.trim_end()));
        assert!(!reference.ends_with("\n\n"));
    }
}
