#!/usr/bin/env python3
"""Generate schema-backed manual chapters and reject drift."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "docs/schemas/config.schema.json"
CONFIG = ROOT / "docs/book/configuration.md"
LUA_SOURCE = ROOT / "docs/lua-api.md"
LUA_BOOK = ROOT / "docs/book/lua-api.md"
MARKER = "<!-- Generated by `scripts/generate-docs.py`; do not edit. -->\n\n"


def resolve(schema: dict[str, object], root: dict[str, object]) -> dict[str, object]:
    ref = schema.get("$ref")
    if not isinstance(ref, str):
        return schema
    prefix = "#/$defs/"
    if not ref.startswith(prefix):
        raise ValueError(f"unsupported schema reference: {ref}")
    name = ref.removeprefix(prefix)
    definitions = root.get("$defs", {})
    if not isinstance(definitions, dict) or name not in definitions:
        raise ValueError(f"missing schema definition: {name}")
    resolved = definitions[name]
    if not isinstance(resolved, dict):
        raise ValueError(f"schema definition is not an object: {name}")
    return resolved


def type_name(schema: dict[str, object], root: dict[str, object]) -> str:
    node = resolve(schema, root)
    enum = node.get("enum")
    if isinstance(enum, list):
        return " / ".join(f"`{value}`" for value in enum)
    kind = node.get("type", "object")
    if kind == "integer" and node.get("format"):
        return str(node["format"])
    if kind == "array":
        return "array"
    return str(kind)


def default_name(schema: dict[str, object], root: dict[str, object]) -> str:
    node = resolve(schema, root)
    if "default" not in node:
        return "—"
    return f"`{json.dumps(node['default'], sort_keys=True)}`"


def rows(
    schema: dict[str, object], root: dict[str, object], prefix: str = ""
) -> list[tuple[str, str, str, str]]:
    node = resolve(schema, root)
    properties = node.get("properties")
    if not isinstance(properties, dict):
        return []
    result: list[tuple[str, str, str, str]] = []
    for name, raw_child in properties.items():
        if not isinstance(raw_child, dict):
            continue
        key = f"{prefix}.{name}" if prefix else name
        child = resolve(raw_child, root)
        child_properties = child.get("properties")
        if isinstance(child_properties, dict):
            result.extend(rows(raw_child, root, key))
            continue
        description = str(raw_child.get("description", child.get("description", "")))
        description = description.replace("|", "\\|").replace("\n", " ")
        result.append((key, type_name(raw_child, root), default_name(raw_child, root), description))
    return result


def generate_config() -> str:
    root = json.loads(SCHEMA.read_text(encoding="utf-8"))
    output = [
        MARKER,
        "# Configuration\n\n",
        "Configuration is layered from package defaults, user TOML, workbook settings, "
        "environment, and CLI overrides. Unknown keys are rejected. `schema = 1` is "
        "required. The table below is generated from `docs/schemas/config.schema.json`.\n\n",
        "| Key | Type | Schema default | Description |\n",
        "|---|---|---|---|\n",
    ]
    for key, kind, default, description in rows(root, root):
        output.append(f"| `{key}` | {kind} | {default} | {description} |\n")
    output.append(
        "\nPackage values are shown in `/usr/share/omacell/default/config.toml`; "
        "schema defaults above describe optional object defaults and constraints, not a "
        "second precedence layer. Use `omacell config show`, `diff`, and `validate` to "
        "inspect the effective configuration.\n"
    )
    return "".join(output)


def generated_files() -> dict[Path, str]:
    return {
        CONFIG: generate_config(),
        LUA_BOOK: MARKER + LUA_SOURCE.read_text(encoding="utf-8"),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale: list[Path] = []
    for path, generated in generated_files().items():
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(generated, encoding="utf-8")
        elif not path.is_file() or path.read_text(encoding="utf-8") != generated:
            stale.append(path.relative_to(ROOT))
    if stale:
        for path in stale:
            print(f"stale generated documentation: {path}", file=sys.stderr)
        print("run scripts/generate-docs.py --write", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
